version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/rentdynamics-py

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/envs/rentdynamics-py
            . ~/envs/rentdynamics-py/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ~/envs/rentdynamics-py
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            mkdir xunit
            . ~/envs/rentdynamics-py/bin/activate
            nosetests --with-xunit --xunit-file=./xunit/xunit.xml

      - run:
         name: Run Backslash
         command: |
           # Download the latest CLI for Linux amd64
           curl https://s3.amazonaws.com/cli-bin.backslash.security/latest/backslashctl-linux-x64 -o backslashctl
           # Verify the checksum of the binary
           echo "$(curl -s https://s3.amazonaws.com/cli-sha.backslash.security/latest/backslashctl-linux-x64.sha256)  backslashctl" | sha256sum -c
           # Modify the permissions of the binary to ensure it is executable
           chmod +x ./backslashctl
           # Create an alias backslashctl of the binary to ensure it is available in other directory
           alias backslashctl="$PWD/backslashctl"
           ./backslashctl analyze --repositoryCloneUrl="${CIRCLE_REPOSITORY_URL}" --analyzedBranch="${CIRCLE_BRANCH}" --baselineBranch="master" --gitProvider="github" --gitProviderOrganization="RentDynamics" --deltaScan=true --authToken="${BACKSLASH_AUTH_TOKEN}"

      - store_test_results:
          path: ./xunit

      - store_artifacts:
          path: ./xunit

      - run:
          name: PyPi Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo pip install --upgrade pip
              sudo pip install twine
              python setup.py sdist
              twine upload --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" dist/*
            fi

workflows:
  build:
    jobs:
      - build:
          context:
            - RentDynamicsGeneral
